name: Release japanpatel0305/sample-website

on:
 push:
  branches:
    - main

jobs:
   
   publish-docker-hub:
     name: publish image to Docker hub
     runs-on: ubuntu-latest
     steps:
        - uses: actions/checkout@v4

        - name: LOgin to Docker hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: build and push image
          uses: docker/build-push-action@v5
          with:
            push: true
            tags: japanpatel0305/sample-website:latest

        - name: Trigger Render deploy
          if: github.ref == 'refs/heads/main'
          env:
              RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
          run: |
              curl -X POST "$RENDER_DEPLOY_HOOK_URL"
